### ISSUE TITLE
Server: Use weocksocket proxy for webclient

### ISSUE THREAD

**Issue by mrpaulblack** [MrPaulBlack/human-dont-get-mad#14]
Use a websocket proxy between the raw java socket and a future webclient. This makes sure that webclients and swing clients can use the same server without rewriting the ClientController.

**Comment by mrpaulblack** [comment]
### Basic docker example:

docker-compose.yml
```yaml
version: '3'

services:
  ludo-server:
    build: .
    restart: always
    command: "java -jar /server.jar --json"
    ports:
      - 2342:2342

 #websockify:
    #image: jwnmulder/websockify:latest
    #restart: always
    #command: "ludo-server:2342 127.0.0.1:80"
    #ports:
      #- 8080:8080
```

Dockerfile
```Dockerfile
FROM openjdk:18-slim-buster

COPY ./server.jar /server.jar

EXPOSE 2342
CMD java -jar /server.jar
```
